"""
Remediation Validation Engine — schema-aware, resource-aware remediation generation.

The bug this exists to fix: remediation was previously generated by formatting a single
hardcoded command STRING per playbook (e.g. always assuming `spec.template.spec`), keyed
only by the finding's `remediation_ref`. That produces syntactically-valid-but-rejected
commands whenever the actual target doesn't have that shape — a bare Pod has `spec`, not
`spec.template.spec`; a CronJob's pod template lives even deeper, at
`spec.jobTemplate.spec.template.spec`. Worse, a controller-owned Pod (the overwhelmingly
common case in a real cluster) would get a `kubectl patch pod ...` command when the fix
needs to go on the Deployment/DaemonSet/StatefulSet that owns it — Pods are largely
immutable once created, so that patch would be rejected outright.

Pipeline (mirrors the requested design 1:1):

    Finding -> resolve resource -> resolve owner -> resolve deployment method ->
    determine mutable field -> determine correct patch path -> validate schema ->
    generate remediation -> validate command -> return remediation

Owner resolution itself happens earlier, at finding-creation time in the owning shard
(see shards/workload_pod_security.py's `ref(ev, res)`), where the Evidence needed to walk
ReplicaSet->Deployment / Job->CronJob is actually available — by the time a Finding
reaches this engine, `finding.resource.owner_kind/owner_name/labels/annotations` are
already resolved as far as the scan could confirm. This engine is a pure function of the
Finding; it never re-touches the cluster.

Accuracy over coverage: whenever any step can't be resolved safely, `generate()` returns
`automatable=False` with a `reason_not_automated` explanation instead of guessing. A
command Kubernetes silently ignores or rejects is worse than admitting "manual review
required".
"""
from __future__ import annotations

import dataclasses
import json
import re
from dataclasses import dataclass, field as _field
from typing import Any, Optional

from .models import Finding, ResourceRef

# --------------------------------------------------------------------------------- #
# Schema knowledge: where does each kind's Pod template actually live?
# --------------------------------------------------------------------------------- #
#: Path *prefix segments* to the PodSpec root for each kind. A FieldPatch's `path` is
#: relative to this — e.g. path="securityContext" on a Deployment means the real API
#: field is spec.template.spec.securityContext; on a CronJob it's
#: spec.jobTemplate.spec.template.spec.securityContext.
POD_SPEC_PATH_PREFIX: dict[str, list[str]] = {
    "Pod": ["spec"],
    "Deployment": ["spec", "template", "spec"],
    "DaemonSet": ["spec", "template", "spec"],
    "StatefulSet": ["spec", "template", "spec"],
    "ReplicaSet": ["spec", "template", "spec"],
    "Job": ["spec", "template", "spec"],
    "CronJob": ["spec", "jobTemplate", "spec", "template", "spec"],
}

#: Controllers whose Pod template can be safely patched — Kubernetes reconciles new Pods
#: from it (a rollout for Deployment/DaemonSet/StatefulSet, future scheduled runs for
#: CronJob). Patching one of these is never rejected for a well-formed field patch.
CONTROLLER_KINDS_PATCHABLE = {"Deployment", "DaemonSet", "StatefulSet", "CronJob"}

#: A Pod's *direct* owner is one of these when it is NOT itself the top-level controller.
#: If shards/workload_pod_security.py couldn't resolve past them (the intermediate
#: object wasn't in the scan's evidence, or it genuinely has no further owner), we land
#: here — and deliberately do NOT guess a rename/target from it (see _validate).
UNRESOLVED_INTERMEDIATE_KINDS = {"ReplicaSet", "Job"}


# --------------------------------------------------------------------------------- #
# System-workload detection (§5)
# --------------------------------------------------------------------------------- #
SYSTEM_NAMESPACES = {"kube-system", "kube-public", "kube-node-lease"}
SYSTEM_NAME_MARKERS = (
    "aws-node", "coredns", "kube-dns", "kube-proxy", "ebs-csi", "efs-csi",
    "metrics-server", "cluster-autoscaler", "vpc-cni", "calico", "cilium",
    "konnectivity",
)

SYSTEM_WORKLOAD_WARNING = (
    "This appears to be a Kubernetes/EKS managed component. Verify vendor "
    "documentation before changing its security context because the recommended "
    "hardening may break cluster functionality."
)


def is_system_workload(namespace: Optional[str], name: Optional[str]) -> bool:
    if (namespace or "").lower() in SYSTEM_NAMESPACES:
        return True
    low = (name or "").lower()
    return any(marker in low for marker in SYSTEM_NAME_MARKERS)


# --------------------------------------------------------------------------------- #
# Deployment-method detection (§6)
# --------------------------------------------------------------------------------- #
def detect_deployment_method(labels: Optional[dict], annotations: Optional[dict]) -> str:
    """Return 'helm' | 'argocd' | 'flux' | 'kubectl' from ownership/tracking markers."""
    labels = labels or {}
    annotations = annotations or {}
    keys = [str(k) for k in list(labels) + list(annotations)]
    if str(labels.get("app.kubernetes.io/managed-by", "")).lower() == "helm":
        return "helm"
    if any("argocd.argoproj.io" in k for k in keys):
        return "argocd"
    if any("fluxcd.io" in k for k in keys):
        return "flux"
    return "kubectl"


HELM_WARNING = (
    "This resource is Helm-managed (app.kubernetes.io/managed-by=Helm). A live "
    "`kubectl patch` will drift from the chart's rendered manifest and be silently "
    "reverted on the next `helm upgrade` / reconcile. Update the chart's values and run "
    "`helm upgrade` instead of patching live."
)
GITOPS_WARNING_TMPL = (
    "This resource is managed by {tool} (GitOps). A live `kubectl patch` will be "
    "reverted on the next sync. Update the manifest tracked in Git and let {tool} "
    "apply it, instead of patching live."
)


# --------------------------------------------------------------------------------- #
# Field-level patch descriptors — schema-aware replacement for hardcoded command strings
# --------------------------------------------------------------------------------- #
@dataclass(frozen=True)
class FieldPatch:
    """Describes ONE fix at the field level, independent of resource kind. The engine
    resolves it to a concrete, schema-correct patch per target kind (§2)."""
    #: dotted path to the field. For a pod-level patch it is relative to the Pod spec root
    #: (see POD_SPEC_PATH_PREFIX), e.g. "securityContext" or "hostPID". For a
    #: container_scoped patch it is relative to the CONTAINER, e.g.
    #: "securityContext.capabilities.drop".
    path: str
    value: Any
    title: str
    scope: str = "pod-template"        # "pod-template" | "object-root"
    #: True → the field lives on a single container, not the pod spec. The engine emits a
    #: STRATEGIC-MERGE patch keyed by the container's `name` (from the finding's evidence),
    #: e.g. containers:[{name: app, securityContext: {...}}]. This is deliberately NOT an
    #: RFC-6902 `add` at containers[0]: json-add fails when an intermediate object
    #: (securityContext, capabilities, resources) doesn't already exist — the common case —
    #: and containers[0] blindly targets the wrong container in a multi-container pod.
    #: Strategic merge creates the intermediates and merges into the container BY NAME.
    container_scoped: bool = False
    #: Can this exact field be changed on an ALREADY-RUNNING, non-controller-owned Pod?
    #: Almost always False — Pod spec is immutable after creation except for a short,
    #: explicit allow-list (container image, activeDeadlineSeconds, tolerations, ...)
    #: that does not include securityContext / host-namespace fields (§4).
    mutable_on_live_pod: bool = False
    references: tuple = ()


FIELD_PATCHES: dict[str, FieldPatch] = {
    "playbook/pod-security-context": FieldPatch(
        path="securityContext",
        value={"runAsNonRoot": True, "seccompProfile": {"type": "RuntimeDefault"}},
        title="Harden pod securityContext (runAsNonRoot + seccompProfile)",
        references=("https://kubernetes.io/docs/tutorials/security/seccomp/",
                    "https://kubernetes.io/docs/concepts/security/pod-security-standards/"),
    ),
    "playbook/run-as-non-root": FieldPatch(
        path="securityContext", value={"runAsNonRoot": True},
        title="Force runAsNonRoot",
        references=("https://kubernetes.io/docs/concepts/security/pod-security-standards/",),
    ),
    "playbook/drop-capabilities": FieldPatch(
        path="securityContext.capabilities.drop", value=["ALL"],
        title="Drop ALL capabilities", container_scoped=True,
        references=("https://kubernetes.io/docs/tasks/configure-pod-container/"
                    "security-context/",),
    ),
    "playbook/read-only-root-fs": FieldPatch(
        path="securityContext.readOnlyRootFilesystem", value=True,
        title="Set readOnlyRootFilesystem", container_scoped=True,
    ),
    "playbook/disable-host-pid": FieldPatch(
        path="hostPID", value=False, title="Disable host PID namespace sharing",
    ),
    "playbook/disable-host-network": FieldPatch(
        path="hostNetwork", value=False, title="Disable host network namespace sharing",
    ),
    "playbook/disable-host-ipc": FieldPatch(
        path="hostIPC", value=False, title="Disable host IPC namespace sharing",
    ),
    "playbook/disable-sa-automount": FieldPatch(
        path="automountServiceAccountToken", value=False,
        title="Disable service-account token automount",
        references=("https://kubernetes.io/docs/tasks/configure-pod-container/"
                    "configure-service-account/#opt-out-of-api-credential-automounting",),
    ),
    "playbook/resource-limits": FieldPatch(
        path="resources.limits",
        value={"cpu": "500m", "memory": "512Mi"},
        title="Set container resource limits (adjust values for the workload)",
        container_scoped=True,
        references=("https://kubernetes.io/docs/concepts/configuration/"
                    "manage-resources-containers/",),
    ),
}


# --------------------------------------------------------------------------------- #
# Result object (§8 output format)
# --------------------------------------------------------------------------------- #
@dataclass
class RemediationResult:
    finding_title: str
    affected_resource: str
    owner_resource: Optional[str]
    root_cause: str
    risk: str
    deployment_method: str
    automatable: bool
    title: Optional[str] = None
    target_kind: Optional[str] = None
    target_name: Optional[str] = None
    remediation_steps: list = _field(default_factory=list)
    kubectl_command: Optional[str] = None
    alternative_yaml: Optional[str] = None
    validation_commands: list = _field(default_factory=list)
    rollback_commands: list = _field(default_factory=list)
    warnings: list = _field(default_factory=list)
    references: list = _field(default_factory=list)
    reason_not_automated: Optional[str] = None

    def as_dict(self) -> dict:
        return {
            "finding": self.finding_title,
            "affected_resource": self.affected_resource,
            "owner_resource": self.owner_resource,
            "root_cause": self.root_cause,
            "risk": self.risk,
            "deployment_method": self.deployment_method,
            "automatable": self.automatable,
            "title": self.title,
            "target_kind": self.target_kind,
            "target_name": self.target_name,
            "remediation_steps": self.remediation_steps,
            "kubectl_command": self.kubectl_command,
            "alternative_yaml": self.alternative_yaml,
            "validation_commands": self.validation_commands,
            "rollback_commands": self.rollback_commands,
            "warnings": self.warnings,
            "references": self.references,
            "reason_not_automated": self.reason_not_automated,
        }

    def render_text(self) -> str:
        lines = [
            f"Finding: {self.finding_title}",
            f"Affected Resource: {self.affected_resource}",
            f"Owner Resource: {self.owner_resource or '(none — standalone)'}",
            f"Root Cause: {self.root_cause}",
            f"Risk: {self.risk}",
            "",
            "Remediation Steps:",
        ]
        lines += [f"  {i}. {s}" for i, s in enumerate(self.remediation_steps, 1)] or \
            ["  (none)"]
        lines.append("")
        if self.automatable and self.kubectl_command:
            lines += ["Correct kubectl command:", f"  $ {self.kubectl_command}", ""]
        else:
            lines += ["This remediation cannot be safely automated.",
                     f"  Reason: {self.reason_not_automated}", ""]
        if self.alternative_yaml:
            lines += ["Alternative YAML:", self.alternative_yaml, ""]
        if self.validation_commands:
            lines += ["Validation commands:"] + \
                [f"  $ {c}" for c in self.validation_commands] + [""]
        if self.rollback_commands:
            lines += ["Rollback commands:"] + \
                [f"  $ {c}" for c in self.rollback_commands] + [""]
        if self.warnings:
            lines += ["Warnings:"] + [f"  ⚠  {w}" for w in self.warnings] + [""]
        if self.references:
            lines += ["References:"] + [f"  - {r}" for r in self.references]
        return "\n".join(lines).rstrip()


# --------------------------------------------------------------------------------- #
# The engine
# --------------------------------------------------------------------------------- #
class RemediationEngine:
    """Schema-aware, resource-aware remediation generator (see module docstring)."""

    def generate(self, finding: Finding) -> RemediationResult:
        res = finding.resource
        risk = f"{finding.severity.label} — {finding.message}"
        method = detect_deployment_method(res.labels, res.annotations)
        warnings: list[str] = []

        owner_str = (f"{res.owner_kind}/{res.owner_name} ({res.namespace})"
                    if res.owner_kind else None)

        if is_system_workload(res.namespace, res.owner_name or res.name):
            warnings.append(SYSTEM_WORKLOAD_WARNING)
        if method == "helm":
            warnings.append(HELM_WARNING)
        elif method in ("argocd", "flux"):
            warnings.append(GITOPS_WARNING_TMPL.format(
                tool="ArgoCD" if method == "argocd" else "Flux"))

        base = dict(finding_title=finding.title, affected_resource=str(res),
                   owner_resource=owner_str, root_cause=finding.message, risk=risk,
                   deployment_method=method)

        field = FIELD_PATCHES.get(finding.remediation_ref or "")
        if field is None:
            return self._legacy_result(finding, warnings, base)

        container_name = finding.evidence.get("container") if field.container_scoped \
            else None
        target_kind, target_name, mode = self._resolve_target(res)
        patchable, reason = self._validate(field, target_kind, target_name, mode,
                                           container_name)

        if not patchable:
            steps = self._manual_steps(field, target_kind, target_name, mode, method, res)
            return RemediationResult(automatable=False, reason_not_automated=reason,
                                     remediation_steps=steps, title=field.title,
                                     target_kind=target_kind, target_name=target_name,
                                     warnings=warnings, references=list(field.references),
                                     **base)

        cmd = self._build_command(field, target_kind, target_name, res.namespace,
                                  container_name)
        yaml_snippet = self._build_yaml(field, target_kind, container_name)
        validation, rollback = self._verify_commands(target_kind, target_name, res.namespace)
        steps = self._automated_steps(target_kind, target_name, res.namespace)
        return RemediationResult(automatable=True, kubectl_command=cmd, title=field.title,
                                 target_kind=target_kind, target_name=target_name,
                                 alternative_yaml=yaml_snippet,
                                 validation_commands=validation,
                                 rollback_commands=rollback, remediation_steps=steps,
                                 warnings=warnings, references=list(field.references),
                                 **base)

    # ------------------------------------------------------------------ #
    # step 1: resolve owner -> which object does remediation actually target?
    # ------------------------------------------------------------------ #
    def _resolve_target(self, res: ResourceRef) -> tuple[str, Optional[str], str]:
        if res.kind != "Pod":
            return res.kind, res.name, "direct"
        if res.owner_kind in CONTROLLER_KINDS_PATCHABLE:
            return res.owner_kind, res.owner_name, "controller"
        if res.owner_kind in UNRESOLVED_INTERMEDIATE_KINDS:
            return res.owner_kind, res.owner_name, "unresolved_intermediate"
        return "Pod", res.name, "standalone"

    # ------------------------------------------------------------------ #
    # step 2: validate schema — does this field/kind/mutability combination actually work?
    # ------------------------------------------------------------------ #
    def _validate(self, field: FieldPatch, target_kind: str, target_name: Optional[str],
                 mode: str, container_name: Optional[str] = None) -> tuple[bool, Optional[str]]:
        if field.scope == "object-root":
            return True, None
        if field.container_scoped and not container_name:
            return False, (
                f"'{field.path}' is a per-container field, but the finding did not record "
                "which container it applies to — so no safely-targeted patch can be built "
                "(a positional guess could harden the wrong container). Identify the "
                "container and set the field on it manually."
            )
        if target_kind not in POD_SPEC_PATH_PREFIX:
            return False, (f"No known Pod-template schema path for kind {target_kind!r} "
                           "— cannot validate a patch path, so no command is generated.")
        if mode == "unresolved_intermediate":
            return False, (
                f"This Pod's direct owner is {target_kind}/{target_name}, which could "
                "not be resolved to a top-level controller (Deployment/CronJob) from "
                "the current scan evidence. Patching an intermediate controller's Pod "
                "template does not update already-running Pods, so an automated fix is "
                "not proposed here — confirm the real owner with `kubectl get "
                f"{target_kind.lower()} {target_name} -o yaml` first."
            )
        if target_kind == "Pod" and not field.mutable_on_live_pod:
            return False, (
                f"'{field.path}' is part of the Pod spec, which is immutable once the "
                "Pod is created — Kubernetes rejects patches to this field on a live "
                "Pod. This Pod has no owning controller, so it must be recreated "
                "directly (there is no Deployment/DaemonSet/etc. to roll out instead)."
            )
        return True, None

    # ------------------------------------------------------------------ #
    # steps 3-4: mutable field -> correct patch path -> command
    # ------------------------------------------------------------------ #
    def _path_segments(self, path: str) -> list[str]:
        out: list[str] = []
        for part in path.split("."):
            m = re.match(r"^([a-zA-Z0-9_]+)\[(\d+)\]$", part)
            if m:
                out.append(m.group(1))
                out.append(m.group(2))
            else:
                out.append(part)
        return out

    def _nest(self, segments: list[str], value: Any) -> dict:
        root: dict = {}
        node = root
        for seg in segments[:-1]:
            node[seg] = {}
            node = node[seg]
        node[segments[-1]] = value
        return root

    def _patch_body(self, field: FieldPatch, target_kind: str,
                    container_name: Optional[str]) -> dict:
        """The strategic-merge patch object for this field on this kind. Container-scoped
        fields are wrapped in a single-element `containers` list keyed by name, so the API
        merges into the right container (by its merge key) and creates any missing
        intermediate objects — neither of which a positional RFC-6902 add would do."""
        if field.scope == "object-root":
            return self._nest([field.path], field.value)
        prefix = POD_SPEC_PATH_PREFIX[target_kind]
        if field.container_scoped:
            container_obj = self._nest(self._path_segments(field.path), field.value)
            container_obj["name"] = container_name
            return self._nest(prefix + ["containers"], [container_obj])
        return self._nest(prefix + self._path_segments(field.path), field.value)

    def _build_command(self, field: FieldPatch, target_kind: str, target_name: str,
                       namespace: Optional[str], container_name: Optional[str] = None) -> str:
        ns = namespace or "default"
        kind_lc = target_kind.lower()
        body = self._patch_body(field, target_kind, container_name)
        return f"kubectl patch {kind_lc} {target_name} -n {ns} -p '{json.dumps(body)}'"

    def _to_yaml_snippet(self, d: dict, indent: int = 0) -> str:
        lines = []
        pad = "  " * indent
        for k, v in d.items():
            if isinstance(v, dict):
                lines.append(f"{pad}{k}:")
                lines.append(self._to_yaml_snippet(v, indent + 1))
            elif isinstance(v, list):
                lines.append(f"{pad}{k}:")
                for item in v:
                    if isinstance(item, dict):
                        lines.append(self._yaml_list_item(item, indent + 1))
                    else:
                        lines.append(f"{pad}  - {item}")
            elif isinstance(v, bool):
                lines.append(f"{pad}{k}: {'true' if v else 'false'}")
            else:
                lines.append(f"{pad}{k}: {v}")
        return "\n".join(lines)

    def _yaml_list_item(self, d: dict, indent: int) -> str:
        """Render a dict as a YAML list item: the FIRST key carries the `- ` marker, and
        every other key of the same map aligns to the column *after* the marker (indent+1),
        so nesting stays valid (e.g. capabilities really lands under securityContext, and
        `name` is a sibling of securityContext — not a stray top-level key)."""
        body_lines = self._to_yaml_snippet(d, indent + 1).split("\n")
        first_pad = "  " * (indent + 1)
        marker = "  " * indent + "- "
        body_lines[0] = marker + body_lines[0][len(first_pad):]
        return "\n".join(body_lines)

    def _build_yaml(self, field: FieldPatch, target_kind: str,
                    container_name: Optional[str] = None) -> str:
        nested = self._patch_body(field, target_kind, container_name)
        return "```yaml\n" + self._to_yaml_snippet(nested) + "\n```"

    def _verify_commands(self, target_kind: str, target_name: str,
                         namespace: Optional[str]) -> tuple[list, list]:
        ns = namespace or "default"
        kind_lc = target_kind.lower()
        validation = [f"kubectl get {kind_lc} {target_name} -n {ns} -o yaml"]
        if target_kind in ("Deployment", "DaemonSet", "StatefulSet"):
            validation.append(f"kubectl rollout status {kind_lc}/{target_name} -n {ns}")
            rollback = [f"kubectl rollout undo {kind_lc}/{target_name} -n {ns}"]
        elif target_kind == "CronJob":
            rollback = [
                f"# snapshot BEFORE applying: kubectl get cronjob {target_name} -n {ns} "
                f"-o yaml > /snapshots/CronJob-{target_name}.yaml",
                f"kubectl apply -f /snapshots/CronJob-{target_name}.yaml",
            ]
        else:
            rollback = [
                f"# snapshot BEFORE applying: kubectl get {kind_lc} {target_name} -n {ns} "
                f"-o yaml > /snapshots/{target_kind}-{target_name}.yaml",
                f"kubectl apply -f /snapshots/{target_kind}-{target_name}.yaml",
            ]
        return validation, rollback

    def _automated_steps(self, target_kind: str, target_name: str,
                         namespace: Optional[str]) -> list[str]:
        ns = namespace or "default"
        steps = []
        if target_kind != "Pod":
            steps.append(f"This Pod is managed by {target_kind} '{target_name}' — the "
                        "fix is applied there, not on the Pod directly (Pods can't be "
                        "patched this way once created).")
        else:
            steps.append("This is a standalone Pod; the field is being patched directly "
                        "(only reached when the field is genuinely mutable on a live Pod).")
        steps += ["Review the exact command below before running it.", "Apply the patch.",
                 "Watch the rollout / re-scan to confirm the finding cleared."]
        if target_kind == "CronJob":
            steps.append(
                "This only affects FUTURE scheduled runs — if a Job/Pod from this "
                "CronJob is already running, delete it manually or trigger a fresh, "
                f"corrected run with: kubectl create job --from=cronjob/{target_name} "
                f"{target_name}-manual -n {ns}"
            )
        return steps

    # ------------------------------------------------------------------ #
    # non-automatable paths — explain, don't guess
    # ------------------------------------------------------------------ #
    def _manual_steps(self, field: FieldPatch, target_kind: str, target_name: Optional[str],
                      mode: str, method: str, res: ResourceRef) -> list[str]:
        ns = res.namespace or "default"
        if mode == "standalone":
            return [
                f"'{field.path}' cannot be patched on a live, standalone Pod.",
                f"kubectl get pod {res.name} -n {ns} -o yaml > pod.yaml",
                "Edit pod.yaml to set the corrected value, then:",
                f"kubectl delete pod {res.name} -n {ns}",
                "kubectl apply -f pod.yaml",
            ]
        if mode == "unresolved_intermediate":
            return [
                f"Confirm the real owner: kubectl get {target_kind.lower()} "
                f"{target_name} -n {ns} -o yaml",
                "If it has its own controller, patch/rollout-restart that controller "
                "instead of this intermediate object.",
                "If it is genuinely standalone, delete and recreate it with a "
                "corrected manifest — its Pod template is not reliably patchable live.",
            ]
        if method == "helm":
            return ["Update the Helm chart's values / template for this field.",
                   "Run: helm upgrade <release> <chart> -f values.yaml"]
        if method in ("argocd", "flux"):
            tool = "ArgoCD" if method == "argocd" else "Flux"
            return [f"Update the manifest tracked by {tool} in Git.",
                   "Commit and push — let the GitOps controller reconcile it."]
        return ["No automated remediation path is available for this finding; edit "
               "the manifest manually and re-apply."]

    def _legacy_result(self, finding: Finding, warnings: list,
                       base: dict) -> RemediationResult:
        """Playbooks that target an unambiguous, non-Pod-shaped kind directly (e.g. a
        ServiceAccount, ClusterRoleBinding, NetworkPolicy) or are pure manual-review
        notes — neither is affected by the Pod/controller schema-shape bug, so they pass
        through the original dataset unchanged."""
        from ..mcp.datasets import PLAYBOOKS
        res = finding.resource
        pb = PLAYBOOKS.get(finding.remediation_ref or "", {})
        ns = res.namespace or "default"
        cmds = []
        for c in pb.get("commands", []):
            try:
                cmds.append(c.format(name=res.name, namespace=ns, kind=res.kind.lower()))
            except Exception:
                cmds.append(c)
        # A command is only "automatable" (safe to copy-paste & run) if it is neither a
        # `#` manual note NOR still carries an unresolved <placeholder> the operator must
        # fill in first (e.g. pin-image-digest's `<image>@sha256:<digest>` — the digest
        # needs a registry lookup we can't do here). Presenting such a template as a
        # ready-to-run command would fail on execution.
        has_placeholder = any(re.search(r"<[^>]+>", c) for c in cmds)
        automatable = (bool(cmds) and not has_placeholder
                       and not any(c.strip().startswith("#") for c in cmds))
        if not finding.remediation_ref:
            reason = "No remediation playbook is registered for this rule."
        elif has_placeholder:
            reason = ("This fix needs a value you must supply before running it (shown as "
                      "<...> in the template below) — e.g. the image digest, which requires "
                      "resolving the tag against the registry first.")
        elif not automatable:
            reason = ("This finding's fix is a manual/policy action, not a single safe "
                     "kubectl command.")
        else:
            reason = None
        return RemediationResult(
            automatable=automatable, title=pb.get("title"),
            target_kind=res.kind if automatable else None,
            target_name=res.name if automatable else None,
            kubectl_command=cmds[0] if automatable else None,
            remediation_steps=(["Review and run the command below."] if automatable
                              else ([pb.get("title", "")] + list(cmds) if cmds else
                                    ["No remediation is registered for this rule."])),
            warnings=warnings, reason_not_automated=reason, **base,
        )


_ENGINE = RemediationEngine()


def generate_remediation(finding: Finding) -> RemediationResult:
    """Module-level convenience wrapper — the engine is stateless."""
    return _ENGINE.generate(finding)
